from setuptools import setup, find_packages

setup(
    name="gmail_assistant_llm",
    version="0.1.0",
    packages=find_packages(),
      install_requires=[
        "numpy",
        "google-api-python-client==2.139.0",
        "google-auth-httplib2==0.2.0",
        "google-auth-oauthlib==1.2.1",
        "langchain==0.2.12",
        "pandas",
        "requests",
        "ipykernel",
        "python-dotenv",
        "beautifulsoup4==4.12.3",
        "openai==1.38.0",
        "langchain-openai==0.1.20",
        "langchain-community==0.2.11",
        "unstructured",
        "matplotlib",
        "seaborn",
        "openpyxl",
    ],
    author="Zihan Ren",
    author_email="zihanren.ds@gmail.com",
    description="LLM driven job assistant that can query, search and summarize based on Gmail contents",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/ZihanRen/job_assistant",
)